# Generated by Django 6.0.6 on 2026-08-11 13:56

import app.fields
import app.models
import django.db.models.deletion
import hashlib
import hmac
import uuid
from datetime import timedelta
from cryptography.fernet import Fernet, InvalidToken
from django.conf import settings
from django.db import migrations, models


def protect_existing_references(apps, schema_editor):
    """Encrypt legacy reference text and backfill non-reversible lookup keys."""
    cipher = Fernet(settings.FIELD_ENCRYPTION_KEY.encode("ascii"))
    digest_key = settings.AUDIT_HMAC_KEY.encode("utf-8")
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            "SELECT id, applicant_reference, created_at, request_id "
            "FROM app_assessmentcase"
        )
        cases = cursor.fetchall()
        case_by_request = {}
        for case_id, reference, created_at, request_id in cases:
            normalized = str(reference or "").strip()
            encrypted = cipher.encrypt(normalized.encode("utf-8")).decode("ascii")
            digest = (
                hmac.new(
                    digest_key,
                    normalized.casefold().encode("utf-8"),
                    hashlib.sha256,
                ).hexdigest()
                if normalized
                else ""
            )
            cursor.execute(
                "UPDATE app_assessmentcase SET applicant_reference = %s, "
                "applicant_reference_digest = %s, due_at = %s WHERE id = %s",
                [encrypted, digest, created_at + timedelta(hours=48), case_id],
            )
            case_by_request[str(request_id)] = case_id

        cursor.execute("SELECT id, request_id FROM app_predictionaudit")
        for audit_id, request_id in cursor.fetchall():
            case_id = case_by_request.get(str(request_id))
            if case_id:
                cursor.execute(
                    "UPDATE app_predictionaudit SET case_id = %s WHERE id = %s",
                    [case_id, audit_id],
                )

    # Backfill the normalized batch-to-case relation from encrypted legacy row
    # summaries without ever copying applicant data into the migration log.
    BatchAssessment = apps.get_model("app", "BatchAssessment")
    with schema_editor.connection.cursor() as cursor:
        for batch in BatchAssessment.objects.all().iterator():
            for row in batch.results:
                case_id = row.get("case_id") if isinstance(row, dict) else None
                if case_id:
                    cursor.execute(
                        "UPDATE app_assessmentcase SET batch_id = %s WHERE id = %s",
                        [batch.id, case_id],
                    )


def restore_plaintext_references(apps, schema_editor):
    cipher = Fernet(settings.FIELD_ENCRYPTION_KEY.encode("ascii"))
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("SELECT id, applicant_reference FROM app_assessmentcase")
        for case_id, encrypted in cursor.fetchall():
            try:
                plaintext = cipher.decrypt(str(encrypted).encode("ascii")).decode("utf-8")
            except (InvalidToken, UnicodeEncodeError):
                plaintext = str(encrypted or "")
            cursor.execute(
                "UPDATE app_assessmentcase SET applicant_reference = %s WHERE id = %s",
                [plaintext, case_id],
            )


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_sensitive_data_access_log'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiRateLimitBucket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_digest', models.CharField(max_length=64)),
                ('window_start', models.DateTimeField()),
                ('request_count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='BatchRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField()),
                ('applicant_reference', app.fields.EncryptedTextField(blank=True)),
                ('reference_digest', models.CharField(blank=True, db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('scored', 'Scored'), ('invalid', 'Invalid'), ('failed', 'Failed'), ('redacted', 'Redacted')], default='pending', max_length=16)),
                ('result', app.fields.EncryptedJSONField(default=dict)),
                ('warnings', app.fields.EncryptedJSONField(default=list)),
                ('errors', app.fields.EncryptedJSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['row_number'],
            },
        ),
        migrations.CreateModel(
            name='CaseOutcome',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('outcome', models.CharField(choices=[('performing', 'Performing'), ('defaulted', 'Defaulted'), ('charged_off', 'Charged off'), ('closed_other', 'Closed - other')], max_length=20)),
                ('outcome_date', models.DateField()),
                ('performance_window_end', models.DateField()),
                ('as_of_date', models.DateField()),
                ('exposure_at_default', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('loss_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('source', models.CharField(max_length=80)),
                ('source_reference', models.CharField(blank=True, max_length=120)),
                ('notes', app.fields.EncryptedTextField(blank=True)),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseReviewEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event_type', models.CharField(choices=[('review', 'Review'), ('assignment', 'Assignment'), ('outcome', 'Outcome recorded')], max_length=20)),
                ('review_version', models.PositiveIntegerField()),
                ('before_state', app.fields.EncryptedJSONField(default=dict)),
                ('after_state', app.fields.EncryptedJSONField(default=dict)),
                ('reason', app.fields.EncryptedTextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DataDeletionReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reference_digest', models.CharField(db_index=True, max_length=64)),
                ('requested_by', models.CharField(max_length=120)),
                ('deleted_cases', models.PositiveIntegerField(default=0)),
                ('deleted_audits', models.PositiveIntegerField(default=0)),
                ('redacted_batch_rows', models.PositiveIntegerField(default=0)),
                ('notes', app.fields.EncryptedTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LegalHoldEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(choices=[('placed', 'Placed'), ('released', 'Released')], max_length=12)),
                ('reason', app.fields.EncryptedTextField()),
                ('ticket_reference', models.CharField(max_length=120)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MonitoringRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('as_of_date', models.DateField()),
                ('window_start', models.DateField()),
                ('window_end', models.DateField()),
                ('model_version', models.CharField(max_length=32)),
                ('model_release_id', models.CharField(blank=True, max_length=96)),
                ('sample_size', models.PositiveIntegerField()),
                ('mature_outcome_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pass', 'Pass'), ('alert', 'Alert'), ('failed', 'Failed')], max_length=12)),
                ('metrics', app.fields.EncryptedJSONField(default=dict)),
                ('alerts', app.fields.EncryptedJSONField(default=list)),
                ('input_digest', models.CharField(max_length=64)),
                ('owner', models.CharField(max_length=120)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PolicyScenario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=12)),
                ('assumptions', app.fields.EncryptedJSONField(default=dict)),
                ('results', app.fields.EncryptedJSONField(default=dict)),
                ('model_version', models.CharField(max_length=32)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PolicyScenarioEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(choices=[('created', 'Created'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=12)),
                ('reason', app.fields.EncryptedTextField()),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='assessmentcase',
            name='applicant_reference_digest',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='assessmentcase',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to='app.batchassessment'),
        ),
        migrations.AddField(
            model_name='assessmentcase',
            name='deployment_stage',
            field=models.CharField(choices=[('local_demo', 'Local demonstration'), ('approved', 'Approved release'), ('unclassified', 'Unclassified')], db_index=True, default='unclassified', max_length=24),
        ),
        migrations.AddField(
            model_name='assessmentcase',
            name='due_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='assessmentcase',
            name='idempotency_namespace',
            field=models.CharField(default='legacy', max_length=96),
        ),
        migrations.AddField(
            model_name='assessmentcase',
            name='model_release_id',
            field=models.CharField(blank=True, max_length=96),
        ),
        migrations.AddField(
            model_name='assessmentcase',
            name='request_digest',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='assessmentcase',
            name='review_version',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assessmentcase',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_assessment_cases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='batchassessment',
            name='attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='batchassessment',
            name='cancel_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='batchassessment',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='batchassessment',
            name='error_message',
            field=app.fields.EncryptedTextField(blank=True),
        ),
        migrations.AddField(
            model_name='batchassessment',
            name='input_file',
            field=models.FileField(blank=True, upload_to=app.models.batch_upload_path),
        ),
        migrations.AddField(
            model_name='batchassessment',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='predictionaudit',
            name='case',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prediction_audit', to='app.assessmentcase'),
        ),
        migrations.AddField(
            model_name='predictionaudit',
            name='deployment_stage',
            field=models.CharField(default='unclassified', max_length=24),
        ),
        migrations.AddField(
            model_name='predictionaudit',
            name='idempotency_namespace',
            field=models.CharField(default='legacy', max_length=96),
        ),
        migrations.AddField(
            model_name='predictionaudit',
            name='request_digest',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.RunPython(
            protect_existing_references,
            reverse_code=restore_plaintext_references,
        ),
        migrations.AlterField(
            model_name='assessmentcase',
            name='applicant_reference',
            field=app.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='assessmentcase',
            name='request_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='batchassessment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('complete', 'Complete'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=16),
        ),
        migrations.AlterField(
            model_name='predictionaudit',
            name='request_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AddIndex(
            model_name='assessmentcase',
            index=models.Index(fields=['assigned_to', 'status', 'due_at'], name='app_assessm_assigne_81eb15_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentcase',
            index=models.Index(fields=['model_version', '-created_at'], name='app_assessm_model_v_0912bc_idx'),
        ),
        migrations.AddIndex(
            model_name='batchassessment',
            index=models.Index(fields=['status', 'created_at'], name='app_batchas_status_4e6334_idx'),
        ),
        migrations.AddIndex(
            model_name='predictionaudit',
            index=models.Index(fields=['model_version', '-created_at'], name='app_predict_model_v_e3bea3_idx'),
        ),
        migrations.AddIndex(
            model_name='predictionaudit',
            index=models.Index(fields=['source', '-created_at'], name='app_predict_source_5e2bed_idx'),
        ),
        migrations.AddConstraint(
            model_name='assessmentcase',
            constraint=models.UniqueConstraint(fields=('idempotency_namespace', 'request_id'), name='uniq_case_namespace_request'),
        ),
        migrations.AddConstraint(
            model_name='predictionaudit',
            constraint=models.UniqueConstraint(fields=('idempotency_namespace', 'request_id'), name='uniq_audit_namespace_request'),
        ),
        migrations.AddConstraint(
            model_name='apiratelimitbucket',
            constraint=models.UniqueConstraint(fields=('key_digest', 'window_start'), name='uniq_api_rate_window'),
        ),
        migrations.AddField(
            model_name='batchrow',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='app.batchassessment'),
        ),
        migrations.AddField(
            model_name='batchrow',
            name='case',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batch_row', to='app.assessmentcase'),
        ),
        migrations.AddField(
            model_name='caseoutcome',
            name='case',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='outcome', to='app.assessmentcase'),
        ),
        migrations.AddField(
            model_name='caseoutcome',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_case_outcomes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='casereviewevent',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_review_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='casereviewevent',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_events', to='app.assessmentcase'),
        ),
        migrations.AddField(
            model_name='legalholdevent',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legal_hold_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='legalholdevent',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_hold_events', to='app.assessmentcase'),
        ),
        migrations.AddField(
            model_name='monitoringrun',
            name='acknowledged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_monitoring_runs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='policyscenario',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_policy_scenarios', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='policyscenario',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='policy_scenarios', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='policyscenarioevent',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='policy_scenario_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='policyscenarioevent',
            name='scenario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='app.policyscenario'),
        ),
        migrations.AddConstraint(
            model_name='batchrow',
            constraint=models.UniqueConstraint(fields=('batch', 'row_number'), name='uniq_batch_row_number'),
        ),
        migrations.AddIndex(
            model_name='caseoutcome',
            index=models.Index(fields=['outcome', 'outcome_date'], name='app_caseout_outcome_2eeecb_idx'),
        ),
        migrations.AddConstraint(
            model_name='casereviewevent',
            constraint=models.UniqueConstraint(fields=('case', 'review_version'), name='uniq_case_review_version'),
        ),
        migrations.AddIndex(
            model_name='monitoringrun',
            index=models.Index(fields=['model_version', '-created_at'], name='app_monitor_model_v_c26519_idx'),
        ),
        migrations.AddConstraint(
            model_name='policyscenario',
            constraint=models.UniqueConstraint(fields=('name', 'version'), name='uniq_policy_name_version'),
        ),
    ]
