# Generated by Django 6.0.6 on 2026-08-11 14:00

import app.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_governance_and_operations'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoringAcknowledgement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(choices=[('acknowledged', 'Acknowledged'), ('escalated', 'Escalated'), ('resolved', 'Resolved')], max_length=16)),
                ('note', app.fields.EncryptedTextField()),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitoring_acknowledgements', to=settings.AUTH_USER_MODEL)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acknowledgements', to='app.monitoringrun')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
