# Generated by Django 6.0.6 on 2026-08-11 14:05

import app.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_monitoring_acknowledgements'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchassessment',
            name='upload_payload',
            field=app.fields.EncryptedBinaryField(blank=True, default=bytes),
        ),
    ]
