# Generated by Django 6.0.6 on 2026-08-11 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_encrypted_batch_payload'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchassessment',
            name='heartbeat_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='batchassessment',
            name='worker_token',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
    ]
